### ISSUE TITLE
目前存在的问题

### ISSUE THREAD

**Issue by fantastao** [Fool-LeoTao/amc#8]
# css样式调整
# 管理页首页的图表，API

系统检测到用户长期不确认收货，自动将订单变成success（或者管理员沟通后有权将订单状态改为success），用户信用值降低
用户修改自己密码
＊erp的mrp：采购单小于安全库存时自动添加，由于采购成本不固定，无法自动添加采购单
# 用户的信用管理，目前只是长期不付款（30天）信用降低处理
# 管理员角色管理
# update产品时disable掉库存字段
# 产品详情页重复购买的问题
# 时间显示处理 列表按照时间排序
# 退货的处理视图还没完成
# 状态显示的时候用中文
# 采购添加价格字段，做付款单
# 错误界面和异常处理，暂时都是用return来替代的
# 后台订单历史纪录呈现，放在订单详情页
# 财务的管理需要修改，后台没有创建权限，只能在到账后修改状态
# 后台用户权限管理
# 危险账单

**Comment by fantastao** [comment]
做完的打#号

**Comment by lijiahong** [comment]
＃css样式调整完成
#退货视图修改完成
#管理员取消订单后修改库存
#管理员取消订单后修改库存的处理
#添加首页图表
#应收账款状态修改，取消创建功能
#采购管理创建时核对产品编号，创建后不得修改，采购结束后可查看详情
#后台订单历史，订单详情页

**Comment by lijiahong** [comment]
#退货视图修改完成
#管理员取消订单后修改库存

**Comment by lijiahong** [comment]
错误界面和异常处理，暂时都是用return来替代的
#css样式调整
采购添加价格字段，做付款单
后台用户权限管理
管理页首页的图表
#退货的处理视图还没完成
财务的管理需要修改，后台没有创建权限，只能在到账后修改状态
状态显示的时候用中文
后台订单历史纪录呈现，放在订单详情页
系统检测到用户长期不确认收货，自动将订单变成success（或者管理员沟通后有权将订单状态改为success），用户信用值降低
＊erp的mrp：采购单小于安全库存时自动添加
＊用户的信用管理

#产品详情页重复购买的问题
#时间显示处理 列表按照时间排序
#管理员取消订单后修改库存的处理

**Comment by lijiahong** [comment]
#我的订单页面订单按修改时间排序

**Comment by lijiahong** [comment]
#添加首页图表
